/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;
import com.mysql.jdbc.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;
import javax.swing.ImageIcon;
import static program.pegawai.nama;
import static program.pembeli.idnama;
import static program.pembeli.nama1;

/**
 *
 * @author SAMSUNG
 */
public class login extends javax.swing.JFrame {
 
    int dragxmouse;
    int dragymouse;
    
    public login() {
        if(koneksi_db.koneksiDb()==null)
        {
            JOptionPane.showMessageDialog(rootPane, "TIDAK ADA KONEKSI!", "CONNECTION...", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }else{
        initComponents();
        setBackground(new Color(0,0,0,0));
        jButton1.setVisible(false);
        jButton1.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Close2.png"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 10, 35, 30));

        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 10, 35, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Minimize2.png"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 10, 35, 30));

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 35, 30));

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 235, 230, 30));

        jPasswordField1.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 338, 210, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Show.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 346, 19, 19));

        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 346, 19, 19));

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 418, 166, 32));

        jButton1.setBackground(new java.awt.Color(173, 184, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("MASUK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 418, 166, 32));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Login.png"))); // NOI18N
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bgMouseMoved(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 630));

        setSize(new java.awt.Dimension(680, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i=0.0;i<=1.0;i=i+0.2)
        {
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }
            catch(InterruptedException ex)
            {
                
            }
        }
        System.out.println(evt); 
    }//GEN-LAST:event_formWindowOpened

    private void bgMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseMoved
        jLabel3.setVisible(false);
        jLabel3.setEnabled(false); 
        jLabel2.setVisible(true);
        jLabel2.setEnabled(true);
        
        jLabel7.setVisible(false);
        jLabel7.setEnabled(false); 
        jLabel6.setVisible(true);
        jLabel6.setEnabled(true);
        
        jButton1.setVisible(false);
        jButton1.setEnabled(false);
        jLabel10.setVisible(true);
        jLabel10.setEnabled(true);
    }//GEN-LAST:event_bgMouseMoved

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y - dragymouse);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        
        jLabel3.setVisible(true);
        jLabel3.setEnabled(true);
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/close.png"));
        jLabel3.setIcon(A);
        jLabel2.setVisible(false);
        jLabel2.setEnabled(false);
        
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        
        jLabel6.setVisible(true);
        jLabel6.setEnabled(true);
        jLabel7.setVisible(false);
        jLabel7.setEnabled(false);
        
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
        jLabel7.setVisible(true);
        jLabel7.setEnabled(true);
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/Minimize.png"));
        jLabel7.setIcon(A);
        jLabel6.setVisible(false);
        jLabel6.setEnabled(false);
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setExtendedState(login.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        
        jLabel2.setVisible(true);
        jLabel2.setEnabled(true);
        jLabel3.setVisible(false);
        jLabel3.setEnabled(false); 
        
    }//GEN-LAST:event_jLabel7MouseMoved

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jLabel9.setVisible(true);
        jLabel9.setEnabled(true);
        jPasswordField1.setEchoChar((char)0);
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/Hide.png"));
        jLabel9.setIcon(A);
        jLabel8.setVisible(false);
        jLabel8.setEnabled(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        jLabel8.setVisible(true);
        jLabel8.setEnabled(true);
        jPasswordField1.setEchoChar((char)8226);
        jLabel9.setVisible(false);
        jLabel9.setEnabled(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
       jButton1.setVisible(true);
       jButton1.setEnabled(true);
       jLabel10.setVisible(false);
       jLabel10.setEnabled(false);
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      ceklogin();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char karakter = evt.getKeyChar();
        if(karakter==KeyEvent.VK_ENTER)
        {
           jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        char karakter = evt.getKeyChar();
        if(karakter==KeyEvent.VK_ENTER)
        {
           ceklogin();
        }
    }//GEN-LAST:event_jPasswordField1KeyTyped
private void ceklogin(){
try{
 if(jTextField1.getText().equals("") || jPasswordField1.getText().equals("")){
 JOptionPane.showMessageDialog(rootPane, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
 jTextField1.requestFocus();
 HapusLayar();
 }else{
 Connection conn = koneksi_db.koneksiDb();
 Statement st = conn.createStatement();
 String sql_pembeli = ("SELECT * FROM pembeli WHERE username = '"+jTextField1.getText()+"' AND password = '"+String.valueOf(jPasswordField1.getPassword())+"'");
 ResultSet rs_pembeli = st.executeQuery(sql_pembeli);
 if(rs_pembeli.next()){
 this.dispose();
 new pembeli().setVisible(true);
 nama1.setText(rs_pembeli.getString(2));
 idnama.setText(rs_pembeli.getString(1));
 }else{
 String sql_pegawai = ("SELECT * FROM pegawai WHERE username = '"+jTextField1.getText()+"' AND password = '"+String.valueOf(jPasswordField1.getPassword())+"'");
 ResultSet rs_pegawai = st.executeQuery(sql_pegawai);
 if(rs_pegawai.next()){
 this.dispose();
 new pegawai().setVisible(true);
 nama.setText(rs_pegawai.getString(2));
 }else{
 JOptionPane.showMessageDialog(rootPane, "User Name dan Password Salah\nAtau Akun Belum Terdaftar", "Pesan",JOptionPane.ERROR_MESSAGE);
 HapusLayar();
 }
 }
 }
 }catch(Exception e){
 e.printStackTrace();
 }
}
    
    
 private void HapusLayar(){
 jTextField1.setText("");
 jPasswordField1.setText("");
 jTextField1.setEnabled(true);
 jPasswordField1.setEnabled(true);
 }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
