/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;
import com.mysql.jdbc.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import javax.swing.ImageIcon;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAMSUNG
 */
public class pegawai extends javax.swing.JFrame {

    int dragxmouse;
    int dragymouse;
    
    public pegawai() {
        initComponents();
       setBackground(new Color(0,0,0,0));
       tanggal_jam();
        tampiltabel();
        tabelreport();
        HapusLayar();
    }
    
    public static void tampiltabel(){
    DefaultTableModel table = new DefaultTableModel();
    
    table.addColumn("ID PRODUK");
    table.addColumn("PRODUK");
    table.addColumn("JENIS");
    table.addColumn("HARGA");
    table.addColumn("STOCK");
    table.addColumn("SATUAN");
    
    try
    {
        Connection kon = koneksi_db.koneksiDb();
        String sql = "SELECT `id_barang`, `produk`, `jenis`, `harga`, `stock`, `satuan` FROM `barang` order by `id_barang` DESC ";
        Statement S = kon.createStatement();
        ResultSet R = S.executeQuery(sql);
        
        while(R.next()){
            table.addRow(new Object[]{
                R.getString(1),
                R.getString(2),
                R.getString(3),
                R.getString(4),
                R.getString(5),
                R.getString(6),
            });
        }
        tableStock.setModel(table);
    }catch(Exception e){
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        pesan = new javax.swing.JLabel();
        stock100 = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pesanPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        stockPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jID = new javax.swing.JLabel();
        textPRODUK = new javax.swing.JTextField();
        textJENIS = new javax.swing.JTextField();
        textHARGA = new javax.swing.JTextField();
        textSTOCK = new javax.swing.JTextField();
        textSATUAN = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JLabel();
        btnHapus = new javax.swing.JLabel();
        btnData2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStock = new javax.swing.JTable();
        bg = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        waktu = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluar.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 120, 40));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home1.png"))); // NOI18N
        home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                homeMouseMoved(evt);
            }
        });
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 345, 243, 50));

        pesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pesan1.png"))); // NOI18N
        pesan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pesanMouseMoved(evt);
            }
        });
        pesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesanMouseClicked(evt);
            }
        });
        getContentPane().add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 399, 243, 50));

        stock100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/stock1.png"))); // NOI18N
        stock100.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                stock100MouseMoved(evt);
            }
        });
        stock100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock100MouseClicked(evt);
            }
        });
        getContentPane().add(stock100, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 453, 243, 50));

        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report1.png"))); // NOI18N
        report.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reportMouseMoved(evt);
            }
        });
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });
        getContentPane().add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 507, 243, 50));

        nama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 40));

        mainPanel.setBackground(new java.awt.Color(228, 228, 228));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        homePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 172, 170, 197));

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        homePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 172, 170, 197));

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 172, 170, 197));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home.png"))); // NOI18N
        homePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 555));

        mainPanel.add(homePanel, "card5");

        pesanPanel.setBackground(new java.awt.Color(228, 228, 228));
        pesanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pesan.png"))); // NOI18N
        pesanPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        mainPanel.add(pesanPanel, "card2");

        stockPanel.setBackground(new java.awt.Color(228, 228, 228));
        stockPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/stock.png"))); // NOI18N
        stockPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 40));

        jID.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockPanel.add(jID, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 119, 190, 38));

        textPRODUK.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textPRODUK.setBorder(null);
        textPRODUK.setOpaque(false);
        stockPanel.add(textPRODUK, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 119, 190, 38));

        textJENIS.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textJENIS.setBorder(null);
        textJENIS.setOpaque(false);
        stockPanel.add(textJENIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 197, 190, 38));

        textHARGA.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textHARGA.setBorder(null);
        textHARGA.setOpaque(false);
        stockPanel.add(textHARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 197, 190, 38));

        textSTOCK.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textSTOCK.setBorder(null);
        textSTOCK.setOpaque(false);
        stockPanel.add(textSTOCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 275, 190, 38));

        textSATUAN.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textSATUAN.setBorder(null);
        textSATUAN.setOpaque(false);
        stockPanel.add(textSATUAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 275, 190, 38));

        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        stockPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 332, 70, 30));

        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        stockPanel.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 331, 70, 30));

        btnData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDataMouseClicked(evt);
            }
        });
        stockPanel.add(btnData, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 320, 48, 49));

        btnData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnData2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/input.png"))); // NOI18N
        stockPanel.add(btnData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 320, 48, 49));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseMoved(evt);
            }
        });

        tableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PRODUK", "JENIS", "HARGA", "STOCK", "SATUAN"
            }
        ));
        tableStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableStock.setSelectionBackground(new java.awt.Color(184, 182, 255));
        tableStock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableStockMouseMoved(evt);
            }
        });
        tableStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStock);

        stockPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 380, 700, 160));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/stockPanel.png"))); // NOI18N
        stockPanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 80, 704, 459));

        mainPanel.add(stockPanel, "card3");

        reportPanel.setBackground(new java.awt.Color(228, 228, 228));
        reportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report.png"))); // NOI18N
        reportPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jScrollPane2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseMoved(evt);
            }
        });

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID TRANSAKSI", "NAMA PEMBELI", "PRODUK BELANJAAN", "JUMLAH BELANJAAN", "SATUAN", "TOTAL HARGA", "WAKTU", "TANGGAL"
            }
        ));
        reportTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reportTableMouseMoved(evt);
            }
        });
        jScrollPane2.setViewportView(reportTable);

        reportPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 730, 480));

        mainPanel.add(reportPanel, "card4");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 60, 750, 550));

        waktu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waktu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 90, 28));

        tgl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 27, 90, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pegawai.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        setSize(new java.awt.Dimension(1000, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i=0.0;i<=1.0;i=i+0.5)
        {
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(25);
            }
            catch(InterruptedException ex)
            {
               
            }
        }
        System.out.println(evt); 
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/keluar.png"));
        jLabel2.setIcon(A);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
        
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan1.png"));
        pesan.setIcon(p);
        
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock1.png"));
        stock100.setIcon(s);
        
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report1.png"));
        report.setIcon(r);
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/logout.png"));
        jLabel2.setIcon(A);
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Anda Yakin Akan Keluar?", "PERINGATAN",dialogBtn);
        if(dialogResult == 0)
        {
        dispose();
        new login().setVisible(true);
        }else{       
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y - dragymouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void homeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseMoved
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home2.png"));
        home.setIcon(h);
        
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan1.png"));
        pesan.setIcon(p);
        
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock1.png"));
        stock100.setIcon(s);
        
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report1.png"));
        report.setIcon(r);
    }//GEN-LAST:event_homeMouseMoved

    private void pesanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesanMouseMoved
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan2.png"));
        pesan.setIcon(p);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
        
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock1.png"));
        stock100.setIcon(s);
        
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report1.png"));
        report.setIcon(r);
    }//GEN-LAST:event_pesanMouseMoved

    private void stock100MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock100MouseMoved
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock2.png"));
        stock100.setIcon(s);
        
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan1.png"));
        pesan.setIcon(p);
        
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report1.png"));
        report.setIcon(r);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
    }//GEN-LAST:event_stock100MouseMoved

    private void reportMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseMoved
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report2.png"));
        report.setIcon(r);
        
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock1.png"));
        stock100.setIcon(s);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
        
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan1.png"));
        pesan.setIcon(p);
    }//GEN-LAST:event_reportMouseMoved

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        HapusLayar();

    }//GEN-LAST:event_homeMouseClicked

    private void pesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesanMouseClicked

        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pesanPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        HapusLayar();
        
    }//GEN-LAST:event_pesanMouseClicked

    private void stock100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock100MouseClicked

        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(stockPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_stock100MouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked

        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(reportPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        HapusLayar();
        
    }//GEN-LAST:event_reportMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pesanPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(stockPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(reportPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
            Connection kon = koneksi_db.koneksiDb();        
            String sql = "UPDATE `barang` SET "+"produk='"+textPRODUK.getText()+"', jenis='"+textJENIS.getText()+"', harga='"+textHARGA.getText()+"', stock='"+textSTOCK.getText()+"', satuan='"+textSATUAN.getText()+"' WHERE "+"id_barang='"+jID.getText()+"'";
        try {
            koneksi_db.koneksiDb().createStatement().execute(sql);
        } catch (SQLException ex) {
        }
        tampiltabel();
        HapusLayar();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void tableStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStockMouseClicked
        textPRODUK.setEnabled(true);
        textJENIS.setEnabled(true);
        textHARGA.setEnabled(true);
        textSTOCK.setEnabled(true);
        textSATUAN.setEnabled(true);
        
        int number = tableStock.getSelectedRow();
        jID.setText(tableStock.getValueAt(number, 0).toString());
        textPRODUK.setText(tableStock.getValueAt(number, 1).toString());
        textJENIS.setText(tableStock.getValueAt(number, 2).toString());
        textHARGA.setText(tableStock.getValueAt(number, 3).toString());
        textSTOCK.setText(tableStock.getValueAt(number, 4).toString());
        textSATUAN.setText(tableStock.getValueAt(number, 5).toString());
    }//GEN-LAST:event_tableStockMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
       
            String sql = "DELETE FROM `barang` WHERE "+"`id_barang`='"+jID.getText()+"'";
            try {
            koneksi_db.koneksiDb().createStatement().execute(sql);
            tampiltabel();
            HapusLayar();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMouseClicked
        btnData.setVisible(false);
        btnData.setEnabled(false);
        tambahData tambahdata = new tambahData();
        tambahdata.setVisible(true);
        tambahdata.pack();
        tambahdata.setLocationRelativeTo(null);
        tambahdata.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_btnDataMouseClicked

    private void jScrollPane1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseMoved
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan1.png"));
        pesan.setIcon(p);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
        
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock1.png"));
        stock100.setIcon(s);
        
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report1.png"));
        report.setIcon(r);
    }//GEN-LAST:event_jScrollPane1MouseMoved

    private void tableStockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStockMouseMoved
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan1.png"));
        pesan.setIcon(p);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
        
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock1.png"));
        stock100.setIcon(s);
        
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report1.png"));
        report.setIcon(r);
    }//GEN-LAST:event_tableStockMouseMoved

    private void jScrollPane2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseMoved
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan1.png"));
        pesan.setIcon(p);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
        
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock1.png"));
        stock100.setIcon(s);
        
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report1.png"));
        report.setIcon(r);
    }//GEN-LAST:event_jScrollPane2MouseMoved

    private void reportTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportTableMouseMoved
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/pesan1.png"));
        pesan.setIcon(p);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
        
        ImageIcon s= new ImageIcon(getClass().getResource("/gambar/stock1.png"));
        stock100.setIcon(s);
        
        ImageIcon r= new ImageIcon(getClass().getResource("/gambar/report1.png"));
        report.setIcon(r);
    }//GEN-LAST:event_reportTableMouseMoved
private void HapusLayar(){
 jID.setText("");
 textPRODUK.setText("");
 textJENIS.setText("");
 textHARGA.setText("");
 textSTOCK.setText("");
 textSATUAN.setText("");
 textPRODUK.setEnabled(false);
 textJENIS.setEnabled(false);
 textHARGA.setEnabled(false);
 textSTOCK.setEnabled(false);
 textSATUAN.setEnabled(false);
 tampiltabel();
 }

public static void tabelreport(){
    DefaultTableModel tbreport = new DefaultTableModel();
    
    tbreport.addColumn("ID TRANSAKSI");
    tbreport.addColumn("PEMBELI");
    tbreport.addColumn("PRODUK");
    tbreport.addColumn("JUMLAH");
    tbreport.addColumn("SATUAN");
    tbreport.addColumn("TOTAL HARGA");
    tbreport.addColumn("WAKTU");
    tbreport.addColumn("TANGGAL");
    
    try
    {
        Connection kon = koneksi_db.koneksiDb();
       // String sql = "SELECT `id_transaksi`,`pembeli`.`nama_pembeli`, `barang`.`produk`,`jumlah`,`barang`.`satuan`, `total_harga`, `transaksi`.`waktu`, `transaksi`.`tanggal` FROM `transaksi`,`pembeli`,`barang` WHERE `transaksi`.`id_pembeli`=`pembeli`.`id_pembeli` AND `transaksi`.`id_barang`=`barang`.`id_barang` order by `waktu` DESC, `tanggal` DESC";
        String sql = "SELECT `id_transaksi`,`nama_pembeli`,`produk`,`jumlah`,`satuan`, `total_harga`,`waktu`,`tanggal` FROM `transaksi` order by `waktu` DESC, `tanggal` DESC";
        Statement St = kon.createStatement();
        ResultSet Rs = St.executeQuery(sql);
        
        while(Rs.next()){
            tbreport.addRow(new Object[]{
                Rs.getString(1),
                Rs.getString(2),
                Rs.getString(3),
                Rs.getString(4),
                Rs.getString(5),
                Rs.getString(6),
                Rs.getString(7),
                Rs.getString(8),
            });
        }
        reportTable.setModel(tbreport);
    }catch(Exception e){    
    }
    }

public void tanggal_jam(){
Thread p=new Thread(){
    public void run(){
        for(;;){
            Calendar cal = new GregorianCalendar();
            int hari = cal.get(Calendar.DAY_OF_MONTH);
            int bulan = cal.get(Calendar.MONTH);
            int tahun = cal.get(Calendar.YEAR);
            tgl.setText(tahun+"/"+(bulan+1)+"/"+hari);
            
            int jam = cal.get(Calendar.HOUR);
            int menit = cal.get(Calendar.MINUTE);
            int detik = cal.get(Calendar.SECOND);
            int AM_PM = cal.get(Calendar.AM_PM);
            
            String day_night = "";
            if (AM_PM==1)
            {
            day_night = "PM";
            }
            else{
            day_night = "AM";
            }
            String waktuu = jam + ":" + menit + ":" + detik + " " + day_night;
            waktu.setText(waktuu);
            
            try{
            sleep(1000);
            }catch (InterruptedException ex){
            Logger.getLogger(pembeli.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
};
p.start();
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    public static final javax.swing.JLabel btnData = new javax.swing.JLabel();
    private javax.swing.JLabel btnData2;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JLabel home;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    public static final javax.swing.JLabel nama = new javax.swing.JLabel();
    private javax.swing.JLabel pesan;
    private javax.swing.JPanel pesanPanel;
    private javax.swing.JLabel report;
    private javax.swing.JPanel reportPanel;
    public static final javax.swing.JTable reportTable = new javax.swing.JTable();
    private javax.swing.JLabel stock100;
    private javax.swing.JPanel stockPanel;
    private static javax.swing.JTable tableStock;
    private javax.swing.JTextField textHARGA;
    private javax.swing.JTextField textJENIS;
    private javax.swing.JTextField textPRODUK;
    private javax.swing.JTextField textSATUAN;
    private javax.swing.JTextField textSTOCK;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
