/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

import com.mysql.jdbc.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import javax.swing.ImageIcon;
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import static program.pegawai.reportTable;

/**
 *
 * @author SAMSUNG
 */
public class pembeli extends javax.swing.JFrame {

    int dragxmouse;
    int dragymouse;

    public pembeli() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        tanggal_jam();
        tampilbarang();

        jPanel1.setVisible(false);
        idnama.setVisible(false);
    }
    private void tampilbarang(){
    DefaultTableModel table = new DefaultTableModel();
    table.addColumn("ID PRODUK");
    table.addColumn("PRODUK");
    table.addColumn("JENIS");
    table.addColumn("HARGA");
    table.addColumn("SATUAN");
    table.addColumn("STOCK");
    String cari = textcari.getText();
    try
    {   Connection kon = koneksi_db.koneksiDb();     
        String sql = "SELECT `id_barang`, `produk`, `jenis`, `harga`, `stock`, `satuan` FROM `barang` WHERE `produk` LIKE '%"+cari+"%' OR `harga` LIKE '%"+cari+"%' OR `jenis` LIKE '%"+cari+"%' order by `jenis` ASC,`harga` DESC,`produk` ASC";
        Statement S = kon.createStatement();
        ResultSet R = S.executeQuery(sql);
        while(R.next()){
            table.addRow(new Object[]{
                R.getString(1),
                R.getString(2),
                R.getString(3),
                R.getString(4),
                R.getString(6),
                R.getString(5),
            });
        }
     tableBarang.setModel(table);
    }catch(Exception e){
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        troli = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        namaProduk = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jumlahStock = new javax.swing.JLabel();
        satuan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kurang = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        tambah = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        beli = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        textcari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        troliPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTroli = new javax.swing.JTable();
        tgl = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluar.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 120, 40));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home1.png"))); // NOI18N
        home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                homeMouseMoved(evt);
            }
        });
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 345, 243, 50));

        troli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/troli1.png"))); // NOI18N
        troli.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                troliMouseMoved(evt);
            }
        });
        troli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                troliMouseClicked(evt);
            }
        });
        getContentPane().add(troli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 399, 243, 50));

        nama1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 40));

        idnama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(idnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 40));

        mainPanel.setBackground(new java.awt.Color(228, 228, 228));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaProduk.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        namaProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(namaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, 30));

        id.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, 30));

        jumlahStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jumlahStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 60, 20));

        satuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 80, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("STOCK :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 50, 20));

        kurang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kurang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kurangMouseClicked(evt);
            }
        });
        jPanel1.add(kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 148, 20, 20));

        jumlah.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 144, 50, 30));

        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });
        jPanel1.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 150, 20, 20));

        total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 257, 190, 30));

        beli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beliMouseClicked(evt);
            }
        });
        jPanel1.add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 333, 153, 37));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Close2.png"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 8, 35, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/beli.png"))); // NOI18N
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 326, 459));

        homePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 326, 459));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseMoved(evt);
            }
        });

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRODUK", "HARGA", "SATUAN", "STOCK"
            }
        ));
        tableBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableBarang.setSelectionBackground(new java.awt.Color(184, 182, 255));
        tableBarang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableBarangMouseMoved(evt);
            }
        });
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);

        homePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 80, 700, 460));

        textcari.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textcari.setForeground(new java.awt.Color(255, 255, 255));
        textcari.setBorder(null);
        textcari.setCaretColor(new java.awt.Color(255, 255, 255));
        textcari.setOpaque(false);
        textcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textcariKeyReleased(evt);
            }
        });
        homePanel.add(textcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 160, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 230, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home.png"))); // NOI18N
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        homePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 570));

        mainPanel.add(homePanel, "card5");

        troliPanel.setBackground(new java.awt.Color(228, 228, 228));
        troliPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                troliPanelMouseMoved(evt);
            }
        });
        troliPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/troli3.png"))); // NOI18N
        troliPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jScrollPane2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseMoved(evt);
            }
        });

        tableTroli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID PRODUK", "PRODUK", "JENIS", "HARGA", "SATUAN", "STOCK"
            }
        ));
        tableTroli.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableTroliMouseMoved(evt);
            }
        });
        jScrollPane2.setViewportView(tableTroli);

        troliPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 710, 470));

        mainPanel.add(troliPanel, "card2");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 60, 750, 550));

        tgl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 27, 90, 28));

        waktu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waktu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 90, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pembeli.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        setSize(new java.awt.Dimension(1000, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i=0.0;i<=1.0;i=i+0.5)
        {
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(25);
            }
            catch(InterruptedException ex)
            {
               
            }
        }
        System.out.println(evt);
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/keluar.png"));
        jLabel2.setIcon(A);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);
        
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli1.png"));
        troli.setIcon(p);
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/logout.png"));
        jLabel2.setIcon(A);
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Anda Yakin Akan Keluar?", "PERINGATAN",dialogBtn);
        if(dialogResult == 0)
        {
            dispose();
            new login().setVisible(true);
        }else{

        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y - dragymouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void homeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseMoved
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home2.png"));
        home.setIcon(h);

        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli1.png"));
        troli.setIcon(p);
    }//GEN-LAST:event_homeMouseMoved

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_homeMouseClicked

    private void troliMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_troliMouseMoved
        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli2.png"));
        troli.setIcon(p);

        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);

    }//GEN-LAST:event_troliMouseMoved

    private void troliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_troliMouseClicked

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        jPanel1.setVisible(false);
        mainPanel.add(troliPanel);
        tabeltroli();
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_troliMouseClicked

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        try{
        tableBarang.setEnabled(false);
        jPanel1.setVisible(true);
        int number = tableBarang.getSelectedRow();
        id.setText(tableBarang.getValueAt(number, 0).toString());
        id.setVisible(false);
        namaProduk.setText(tableBarang.getValueAt(number, 1).toString());
        jumlahStock.setText(tableBarang.getValueAt(number, 5).toString());
        satuan.setText(tableBarang.getValueAt(number, 4).toString());
        jumlah.setText(Integer.toString(Integer.parseInt(tableBarang.getValueAt(number, 5).toString())/Integer.parseInt(tableBarang.getValueAt(number, 5).toString())));
        total.setText(tableBarang.getValueAt(number, 3).toString());
        }catch(Exception e){
            jPanel1.setVisible(false);
            tableBarang.setEnabled(true);
        }
    }//GEN-LAST:event_tableBarangMouseClicked

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
        ImageIcon c= new ImageIcon(getClass().getResource("/gambar/close.png"));
        jLabel5.setIcon(c);
    }//GEN-LAST:event_jLabel5MouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        ImageIcon c= new ImageIcon(getClass().getResource("/gambar/Close2.png"));
        jLabel5.setIcon(c);
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        tableBarang.setEnabled(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        ImageIcon c= new ImageIcon(getClass().getResource("/gambar/Close2.png"));
        jLabel5.setIcon(c);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);

        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli1.png"));
        troli.setIcon(p);
        
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/keluar.png"));
        jLabel2.setIcon(A);
    }//GEN-LAST:event_jLabel9MouseMoved

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked

       int i=Integer.parseInt(jumlah.getText());
       int number = tableBarang.getSelectedRow();
       int stock=Integer.parseInt(tableBarang.getValueAt(number, 5).toString());
       i=i+1;
       if(i<=stock){
       jumlah.setText(Integer.toString(i));
       int ttharga=Integer.parseInt(total.getText());
       int tem=Integer.parseInt(tableBarang.getValueAt(number, 3).toString());
       ttharga=tem*i;
       total.setText(Integer.toString(ttharga));
       }
    }//GEN-LAST:event_tambahMouseClicked

    private void kurangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kurangMouseClicked
       int i=Integer.parseInt(jumlah.getText());
       int number = tableBarang.getSelectedRow();
       i=i-1;
       if(i>0){
       jumlah.setText(Integer.toString(i));
       int ttharga=Integer.parseInt(total.getText());
       int tem=Integer.parseInt(tableBarang.getValueAt(number, 3).toString());
       ttharga=tem*i;
       total.setText(Integer.toString(ttharga));
    }
    }//GEN-LAST:event_kurangMouseClicked

    private void beliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beliMouseClicked

        String sql_beli="INSERT INTO `transaksi`(`id_transaksi`, `id_barang`,`produk`, `jumlah`, `satuan`, `total_harga`, `id_pembeli`,`nama_pembeli`, `waktu`, `tanggal`) VALUES (NULL, '"+id.getText()+"', '"+namaProduk.getText()+"', '"+jumlah.getText()+"', '"+satuan.getText()+"', '"+total.getText()+"', '"+idnama.getText()+"', '"+nama1.getText()+"', '"+waktu.getText()+"', '"+tgl.getText()+"')";
        try{
        koneksi_db.koneksiDb().createStatement().executeUpdate(sql_beli);
        jPanel1.setVisible(false);
        tableBarang.setEnabled(true);
        
        }catch(Exception e){
    }
        tampilbarang();
    }//GEN-LAST:event_beliMouseClicked

    private void textcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textcariKeyReleased
        tampilbarang();
    }//GEN-LAST:event_textcariKeyReleased

    private void jScrollPane1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseMoved
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);

        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli1.png"));
        troli.setIcon(p);
        
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/keluar.png"));
        jLabel2.setIcon(A);
    }//GEN-LAST:event_jScrollPane1MouseMoved

    private void jScrollPane2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseMoved
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);

        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli1.png"));
        troli.setIcon(p);
        
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/keluar.png"));
        jLabel2.setIcon(A);
    }//GEN-LAST:event_jScrollPane2MouseMoved

    private void troliPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_troliPanelMouseMoved
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/keluar.png"));
        jLabel2.setIcon(A);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);

        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli1.png"));
        troli.setIcon(p);
    }//GEN-LAST:event_troliPanelMouseMoved

    private void tableTroliMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTroliMouseMoved
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/keluar.png"));
        jLabel2.setIcon(A);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);

        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli1.png"));
        troli.setIcon(p);
    }//GEN-LAST:event_tableTroliMouseMoved

    private void tableBarangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseMoved
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/keluar.png"));
        jLabel2.setIcon(A);
        
        ImageIcon h= new ImageIcon(getClass().getResource("/gambar/home1.png"));
        home.setIcon(h);

        ImageIcon p= new ImageIcon(getClass().getResource("/gambar/troli1.png"));
        troli.setIcon(p);
    }//GEN-LAST:event_tableBarangMouseMoved
public void tanggal_jam(){
Thread p=new Thread(){
    public void run(){
        for(;;){
            Calendar cal = new GregorianCalendar();
            int hari = cal.get(Calendar.DAY_OF_MONTH);
            int bulan = cal.get(Calendar.MONTH);
            int tahun = cal.get(Calendar.YEAR);
            tgl.setText(tahun+"/"+(bulan+1)+"/"+hari);
            
            int jam = cal.get(Calendar.HOUR);
            int menit = cal.get(Calendar.MINUTE);
            int detik = cal.get(Calendar.SECOND);
            int AM_PM = cal.get(Calendar.AM_PM);
            
            String day_night = "";
            if (AM_PM==1)
            {
            day_night = "PM";
            }
            else{
            day_night = "AM";
            }
            String waktuu = jam + ":" + menit + ":" + detik + " " + day_night;
            waktu.setText(waktuu);
            
            try{
            sleep(1000);
            }catch (InterruptedException ex){
            Logger.getLogger(pembeli.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
};
p.start();
}

private void tabeltroli(){
    DefaultTableModel tbtroli = new DefaultTableModel();

    tbtroli.addColumn("PRODUK BELANJAAN");
    tbtroli.addColumn("JUMLAH BELANJAAN");
    tbtroli.addColumn("SATUAN");
    tbtroli.addColumn("TANGGAL");
    
    try
    {
        Connection kon = koneksi_db.koneksiDb();
        //String sql45 = "SELECT `barang`.`produk`,SUM(jumlah) AS `jumlah`,`barang`.`satuan`,`tanggal` FROM `transaksi`,`pembeli`,`barang` WHERE `transaksi`.`id_pembeli`='"+idnama.getText()+"'=`pembeli`.`id_pembeli` AND `transaksi`.`id_barang`=`barang`.`id_barang` GROUP BY `barang`.`produk`,`tanggal` order by `tanggal` DESC";
          String sql45 = "SELECT `produk`,SUM(jumlah) AS `jumlah`,`satuan`,`tanggal` FROM `transaksi` WHERE `id_pembeli`='"+idnama.getText()+"' GROUP BY `produk`,`tanggal` order by `tanggal` DESC";
        Statement Stt = kon.createStatement();
        ResultSet Rss = Stt.executeQuery(sql45);
        
        while(Rss.next()){
            tbtroli.addRow(new Object[]{
                Rss.getString(1),
                Rss.getString(2),
                Rss.getString(3),
                Rss.getString(4),
           
            });
        }
        tableTroli.setModel(tbtroli);
    }catch(Exception e){    
    }
    }

    /*private void HapusLayar(){
 namaProduk.setText("");
 jumlahStock.setText("");
 jumlah.setText("");
 total.setText("");
}*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beli;
    private javax.swing.JLabel home;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel id;
    public static final javax.swing.JLabel idnama = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel jumlahStock;
    private javax.swing.JLabel kurang;
    private javax.swing.JPanel mainPanel;
    public static final javax.swing.JLabel nama1 = new javax.swing.JLabel();
    private javax.swing.JLabel namaProduk;
    private javax.swing.JLabel satuan;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTable tableTroli;
    private javax.swing.JLabel tambah;
    private javax.swing.JTextField textcari;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel total;
    private javax.swing.JLabel troli;
    private javax.swing.JPanel troliPanel;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
