/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;
import com.mysql.jdbc.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import javax.swing.ImageIcon;
import java.awt.Color;

import java.awt.Color;
import java.awt.event.KeyEvent;
import static program.pegawai.btnData;
import static program.pegawai.tampiltabel;

/**
 *
 * @author SAMSUNG
 */
public class tambahData extends javax.swing.JFrame {

    int dragxmouse;
    int dragymouse;
    public tambahData() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tID = new javax.swing.JTextField();
        tPRODUK = new javax.swing.JTextField();
        tJENIS = new javax.swing.JTextField();
        tHARGA = new javax.swing.JTextField();
        tSTOCK = new javax.swing.JTextField();
        tSATUAN = new javax.swing.JTextField();
        btnTambah = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tID.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tID.setBorder(null);
        tID.setOpaque(false);
        tID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tIDKeyTyped(evt);
            }
        });
        getContentPane().add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 108, 190, 38));

        tPRODUK.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tPRODUK.setBorder(null);
        tPRODUK.setOpaque(false);
        getContentPane().add(tPRODUK, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 108, 190, 38));

        tJENIS.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tJENIS.setBorder(null);
        tJENIS.setOpaque(false);
        getContentPane().add(tJENIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 186, 190, 38));

        tHARGA.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tHARGA.setBorder(null);
        tHARGA.setOpaque(false);
        tHARGA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tHARGAKeyTyped(evt);
            }
        });
        getContentPane().add(tHARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 186, 190, 38));

        tSTOCK.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tSTOCK.setBorder(null);
        tSTOCK.setOpaque(false);
        tSTOCK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tSTOCKKeyTyped(evt);
            }
        });
        getContentPane().add(tSTOCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 264, 190, 38));

        tSATUAN.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tSATUAN.setBorder(null);
        tSATUAN.setOpaque(false);
        getContentPane().add(tSATUAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 264, 190, 38));

        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 338, 153, 37));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Close2.png"))); // NOI18N
        exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitMouseMoved(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 4, 35, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Minimize2.png"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 4, 35, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambahPanel.png"))); // NOI18N
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backgroundMouseMoved(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 704, 459));

        setSize(new java.awt.Dimension(704, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y - dragymouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
            
            String sql = "INSERT INTO `barang`(`id_barang`, `produk`, `jenis`, `harga`, `stock`, `satuan`) VALUES ('"+tID.getText()+"','"+tPRODUK.getText()+"','"+tJENIS.getText()+"','"+tHARGA.getText()+"','"+tSTOCK.getText()+"','"+tSATUAN.getText()+"')";
        try{
            koneksi_db.koneksiDb().createStatement().executeUpdate(sql);
            btnData.setVisible(true);
            btnData.setEnabled(true);
            this.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Data Tidak Bisa Ditambah", "Pesan",JOptionPane.ERROR_MESSAGE);
        }
        tampiltabel();
    }//GEN-LAST:event_btnTambahMouseClicked

    private void exitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMoved

        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/close.png"));
        exit.setIcon(A);
        ImageIcon B= new ImageIcon(getClass().getResource("/gambar/Minimize2.png"));
        jLabel6.setIcon(B);

    }//GEN-LAST:event_exitMouseMoved

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved

        ImageIcon B= new ImageIcon(getClass().getResource("/gambar/Minimize.png"));
        jLabel6.setIcon(B);
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/Close2.png"));
        exit.setIcon(A);
    }//GEN-LAST:event_jLabel6MouseMoved

    private void backgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseMoved
        ImageIcon A= new ImageIcon(getClass().getResource("/gambar/Close2.png"));
        exit.setIcon(A);
        ImageIcon B= new ImageIcon(getClass().getResource("/gambar/Minimize2.png"));
        jLabel6.setIcon(B);
    }//GEN-LAST:event_backgroundMouseMoved

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
        btnData.setVisible(true);
        btnData.setEnabled(true);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setExtendedState(tambahData.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tHARGAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tHARGAKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0')&&(karakter <= '9')||(karakter == KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE))))
        {
           getToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_tHARGAKeyTyped

    private void tSTOCKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSTOCKKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0')&&(karakter <= '9')||(karakter == KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE))))
        {
           getToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_tSTOCKKeyTyped

    private void tIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIDKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0')&&(karakter <= '9')||(karakter == KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE))))
        {
           getToolkit().beep();
           evt.consume();
        }
    }//GEN-LAST:event_tIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tHARGA;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tJENIS;
    private javax.swing.JTextField tPRODUK;
    private javax.swing.JTextField tSATUAN;
    private javax.swing.JTextField tSTOCK;
    // End of variables declaration//GEN-END:variables

}
